# ==========================================================================
# FICHIER DE CONFIGURATION NETLIFY POUR BMS VENTOUSE (CORRIGÉ POUR SITE STATIQUE)
# ==========================================================================
# Ce fichier centralise la configuration du build et des déploiements sur Netlify.

# --------------------------------------------------------------------------
# SECTION BUILD : Instructions pour construire le site
# --------------------------------------------------------------------------
[build]
  # Pour un site statique simple, il n'y a pas de commande de build.
  # On laisse cette ligne vide.
  command = ""

  # Le dossier à publier est la racine du projet, où se trouve index.html.
  # C'est la correction la plus importante.
  publish = "."

# --------------------------------------------------------------------------
# SECTION HEADERS : En-têtes HTTP pour la sécurité et la performance
# --------------------------------------------------------------------------
# Ces règles sont conservées car elles sont excellentes pour la sécurité.

[[headers]]
  # Applique ces en-têtes à toutes les pages du site.
  for = "/*"
  [headers.values]
    # Sécurité : Empêche le clickjacking.
    X-Frame-Options = "DENY"
    # Sécurité : Empêche le navigateur de "deviner" le type de contenu.
    X-Content-Type-Options = "nosniff"
    # Sécurité : Active la protection contre les attaques XSS (Cross-Site Scripting).
    X-XSS-Protection = "1; mode=block"
    # Sécurité & Vie Privée : Contrôle les informations envoyées lors de la navigation.
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Sécurité : Bloque les fonctionnalités sensibles du navigateur.
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), usb=()"

[[headers]]
  # Applique une politique de cache longue pour les assets qui ne changent pas souvent.
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


# --------------------------------------------------------------------------
# SECTION REDIRECTS : Redirections d'URL
# --------------------------------------------------------------------------
# Ces règles sont conservées.

[[redirects]]
  # Redirige les anciennes URLs vers la page d'accueil.
  from = "/accueil"
  to = "/"
  status = 301 # Redirection permanente (bon pour le SEO)

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Redirection pour les ancres (si nécessaire)
[[redirects]]
  from = "/services"
  to = "/#services" # Exemple si vous aviez une ancre sur la page d'accueil
  status = 301

# Règle "catch-all" pour les erreurs 404.
# Il est préférable de laisser Netlify gérer la 404 par défaut.
# Si vous avez une page 404.html personnalisée, vous pouvez la spécifier ici.
# Pour l'instant, nous laissons la gestion par défaut de Netlify en ne mettant pas de règle "catch-all" 404.
# Si vous voulez absolument rediriger toutes les pages non trouvées vers l'accueil (non recommandé pour le SEO) :
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
